### PR TITLE
Support Symfony 4.0 (fixes #5)

### LINKED ISSUE #5: Support Symfony 4.0
Hello,

Do you have any plan to support Symfony 4.0?

### PR DESCRIPTION
**Pull request by Rudloff**
As far as I can tell, everything seems to work correctly.

### CODE REVIEW

**Comment by Rudloff** [comment]
PHP 5.3 tests are failing but it is unrelated (PHP 5.3 is not available anymore on current Travis images).

**Comment by krichprollsch** [comment]
Thank you for the PR 🎉 

To fix the tests and improve them we can do:
* drop the php5.3, 5.4, 5.5 support from travis since these php versions are no more officially supported
* drop hhvm quite useless because php7 is so fast 🚀 
* add php7.0 php7.1 and php7.2

WDYT ?

**Comment by Rudloff** [comment]
Hum, it seems the PHP 7 images on Travis use phpunit 6 and your tests are written for phpunit 5.
One solution would be to install a local phpunit 5 with Composer and use it instead of the globally installed one.
Would you be OK with this?

**Comment by krichprollsch** [comment]
yes, I agree for the phpunit deps as a dev requirement 👍

**Comment by krichprollsch** [comment]
ty very much @Rudloff

**Pull request merged**
